from tensorflow/tensorflow:latest-gpu

run apt-get update
run apt-get install -y python-pip python-dev build-essential
run pip install scikit-image
run pip install --upgrade pip
run pip install --upgrade virtualenv
run pip install numpy
run pip install scipy
run pip install EasyDict
run pip install matplotlib
run pip install keras
